# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-19 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('1', 'Annual'), ('2', 'Sick'), ('3', 'Emergency'), ('4', 'Casual')], max_length=1)),
                ('num_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Approved'), ('3', 'Declined')], default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(default='/static/images/default', upload_to=b'')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
                ('DOE', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=b'')),
            ],
        ),
    ]
