# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilepic', models.FileField(default='/default', upload_to=b'')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('DOB', models.DateField()),
                ('DOE', models.DateField()),
                ('position', models.CharField(default='position', max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('appointment_type', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to=b'')),
            ],
        ),
    ]
