# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20180925_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='document',
            field=models.CharField(choices=[('cv', 'cv'), ('birth_certificate', 'birth_certificate'), ('ssce_certificate', 'ssce_certificate'), ('OND_certificate', 'OND_certificate'), ('valid_ID_card', 'valid_ID_card'), ('first_degree_certificate', 'first_degree_certificate'), ('NYSC_certificate', 'NYSC_certificate'), ('MSc_certificate', 'MSc_certificate')], default='select document to upload', max_length=50, null=True),
        ),
    ]
