# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20180925_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='email',
            field=models.EmailField(default='--------------', max_length=254),
        ),
    ]
