# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_documents_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
