# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0013_auto_20180927_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='total_salary_yearly',
        ),
    ]
